use_frameworks!

target 'WSWebKit_Example' do
  pod 'WSWebKit', :path => '../'

  target 'WSWebKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
